apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-keycloak
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: keycloak
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: keycloak
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
        - name: keycloak
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
            - "start-dev"
            - "--http-port={{ .Values.service.port }}"
            {{- if .Values.realm.import }}
            - "--import-realm"
            {{- end }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
          env:
            - name: KEYCLOAK_ADMIN
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-keycloak
                  key: admin-user
            - name: KEYCLOAK_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-keycloak
                  key: admin-password
            {{- if .Values.route.path }}
            - name: KC_HTTP_RELATIVE_PATH
              value: {{ printf "/%s" (trimAll "/" .Values.route.path) | quote }}
            {{- end }}
            {{- with .Values.extraEnv }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
          {{- if .Values.realm.import }}
          volumeMounts:
            - name: realm-config
              mountPath: /opt/keycloak/data/import
              readOnly: true
          {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- if .Values.realm.import }}
      volumes:
        - name: realm-config
          configMap:
            name: {{ .Release.Name }}-keycloak-realm
      {{- end }}
