{{- if .Values.realm.import }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-keycloak-realm
  labels:
    app.kubernetes.io/name: keycloak
    app.kubernetes.io/instance: {{ .Release.Name }}
data:
  gaia-x-realm.json: |-
{{ tpl (.Files.Get "files/gaia-x-realm.json.tpl") . | indent 4 }}
{{- end }}
