apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-keycloak
type: Opaque
stringData:
  admin-user: {{ .Values.auth.adminUser | quote }}
  admin-password: {{ .Values.auth.adminPassword | quote }}
